name: Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world"
    - run: ls
    - uses: actions/checkout@v2
    - run: ls
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: jaager
          password: dckr_pat_fqtcnOtRuocyWYumDdXYQYA556s
    - name: Build and push to dockerhub (jaager/getting-started)
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jaager/getting-started
    - run: jaager/getting-started/latest
    
    
